import './style.css';
import { LIMITS, ScoringSystem } from './domain/models';
import { reverseScore, scoreRange } from './domain/scoring';

const app = document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML = `<header><div class="brand">太鼓计分研究所 <span>POC</span></div><h1>把每一次敲击，<em>算得明明白白。</em></h1><p>旧作街机计分规则 · 本地计算 · 数据不会上传</p></header>
<main><nav><button class="active" data-mode="forward">由成绩推算分数</button><button data-mode="reverse">由总分反推成绩</button></nav>
<section id="forward"><h2>输入成绩</h2><form id="forward-form"><div class="grid"><label>良<input name="good" type="number" min="0" max="${LIMITS.notes}" value="100" required></label><label>可<input name="ok" type="number" min="0" max="${LIMITS.notes}" value="5" required></label><label>不可<input name="bad" type="number" min="0" max="${LIMITS.notes}" value="1" required></label><label>连打数 <small>敲击次数</small><input name="drumroll" type="number" min="0" max="${LIMITS.drumroll}" value="20" required></label></div><div class="config"></div><button class="primary">计算分数范围 →</button></form><div class="result" aria-live="polite"></div></section>
<section id="reverse" hidden><h2>输入目标与谱面约束</h2><form id="reverse-form"><div class="grid"><label>目标总分<input name="score" type="number" min="0" max="${LIMITS.score}" value="105000" required></label><label>总音符数 <small>上限 ${LIMITS.reverseNotes}</small><input name="totalNotes" type="number" min="0" max="${LIMITS.reverseNotes}" value="10" required></label><label>最大连打数<input name="maxDrumroll" type="number" min="0" max="${LIMITS.drumroll}" value="20" required></label><label>已知良 <small>可留空</small><input name="knownGood" type="number" min="0" max="${LIMITS.notes}"></label><label>已知可 <small>可留空</small><input name="knownOk" type="number" min="0" max="${LIMITS.notes}"></label><label>已知不可 <small>可留空</small><input name="knownBad" type="number" min="0" max="${LIMITS.notes}"></label></div><div class="config"></div><button class="primary">搜索候选组合 →</button></form><div class="result" aria-live="polite"></div></section></main><footer>TAIKO SCORE LAB / 计算结果仅供研究核对</footer>`;

function configHtml(prefix: string) { return `<fieldset><legend>计分制</legend><label class="radio"><input type="radio" name="system" value="standard" checked> 非真打</label><label class="radio"><input type="radio" name="system" value="shinuchi"> 真打</label></fieldset><div class="params"><label>初项<input name="initial" type="number" min="0" max="${LIMITS.initial}" value="1000" required></label><label>公差<input name="difference" type="number" min="0" max="${LIMITS.difference}" value="100" required></label></div><p class="hint" id="${prefix}-hint">非真打按连击阶段提升单音符分数</p>`; }
document.querySelectorAll<HTMLElement>('.config').forEach((el, i) => el.innerHTML = configHtml(i ? 'r' : 'f'));
document.querySelectorAll<HTMLButtonElement>('nav button').forEach(b => b.onclick = () => { document.querySelectorAll('nav button').forEach(x => x.classList.toggle('active',x===b)); document.querySelectorAll('main section').forEach(s => s.toggleAttribute('hidden',s.id!==b.dataset.mode)); });
document.querySelectorAll<HTMLInputElement>('input[name=system]').forEach(r => r.onchange = () => { const form=r.closest('form')!; const shin=r.value==='shinuchi'&&r.checked; form.querySelector<HTMLElement>('.params')!.hidden=shin; form.querySelectorAll<HTMLInputElement>('.params input').forEach(x=>x.disabled=shin); });
const number = (fd: FormData, key: string) => Number(fd.get(key));
function config(fd: FormData) { const system=fd.get('system') as ScoringSystem; return {system,initial:system==='shinuchi'?0:number(fd,'initial'),difference:system==='shinuchi'?0:number(fd,'difference')}; }
function errorBox(e: unknown) { return `<div class="error">${e instanceof Error ? e.message : '参数不完整，请检查输入'}</div>`; }
const forwardForm=document.querySelector<HTMLFormElement>('#forward-form')!;
forwardForm.onsubmit = e => { e.preventDefault(); const fd=new FormData(forwardForm); const out=forwardForm.nextElementSibling as HTMLElement; try { const r=scoreRange({good:number(fd,'good'),ok:number(fd,'ok'),bad:number(fd,'bad'),drumroll:number(fd,'drumroll'),config:config(fd)}); out.innerHTML=r.exact?`<h3>确定分数</h3><strong>${r.minimum.toLocaleString()}</strong><p>所有判定排列均得到相同分数。</p>`:`<h3>可能分数范围</h3><div class="range"><strong>${r.minimum.toLocaleString()}</strong><i>至</i><strong>${r.maximum.toLocaleString()}</strong></div><p>范围取决于良、可、不可的排列：不可会中断连击，不同排列进入计分阶段的时机不同。</p>`; } catch(err){out.innerHTML=errorBox(err)} };
const reverseForm=document.querySelector<HTMLFormElement>('#reverse-form')!;
reverseForm.onsubmit = e => { e.preventDefault(); const fd=new FormData(reverseForm); const out=reverseForm.nextElementSibling as HTMLElement; try { const optional=(key:string)=>{const raw=fd.get(key)?.toString();return raw?Number(raw):undefined}; const r=reverseScore(number(fd,'score'),config(fd),{totalNotes:number(fd,'totalNotes'),maxDrumroll:number(fd,'maxDrumroll'),knownGood:optional('knownGood'),knownOk:optional('knownOk'),knownBad:optional('knownBad')}); if(!r.total){out.innerHTML='<div class="error">无解：当前谱面约束下没有候选组合。</div>';return} out.innerHTML=`<h3>找到 ${r.total} 个候选${r.truncated?'（仅展示前 50 个）':''}</h3><div class="table"><table><thead><tr><th>良</th><th>可</th><th>不可</th><th>连打</th><th>复算分数</th></tr></thead><tbody>${r.candidates.map(c=>`<tr><td>${c.good}</td><td>${c.ok}</td><td>${c.bad}</td><td>${c.drumroll}</td><td>${c.score.toLocaleString()}${c.range.exact?'':`<small>（范围 ${c.range.minimum.toLocaleString()}–${c.range.maximum.toLocaleString()}）</small>`}</td></tr>`).join('')}</tbody></table></div><p>非确定候选表示目标位于排列得分上下界内，需结合实际判定顺序进一步核对。</p>`; }catch(err){out.innerHTML=errorBox(err)} };
